
ALTER TABLE public.branches
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS manager_id BIGINT,
  ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.branches DROP COLUMN IF EXISTS manager;

ALTER TABLE public.warehouses
  ADD COLUMN IF NOT EXISTS location TEXT,
  ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.warehouses DROP COLUMN IF EXISTS manager;

ALTER TABLE public.contacts
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT;
